export const label = {
    zh: {
        title: "稱謂",
        firstName: "英文名",
        lastName: "英文姓氏",
        chineseName: '中文姓名',
        email: '電子信箱',
        email2: '電子信箱確認',
        password: '密碼',
        confirmPassword: '確認密碼',
        affiliation: '所屬機構',
        jobTitle: '職稱',
        idCard: '身分證字號',
        country: '國家',
        remitAccountLast5: '匯款帳號末五碼',
        countryCode: '聯絡電話',
        phoneNum: '手機號碼',
        receipt: '發票抬頭',
        category: '類別',
        food: '餐食偏好',
        foodTaboo: '餐食禁忌',
        foodRadio1: '葷食',
        foodRadio2: '素食',
        titleValidate: '請選擇稱謂',
        firstNameValidate: '請輸入英文名',
        lastNameValidate: '請輸入英文姓氏',
        chineseNameValidate: '請輸入中文姓名',
        emailValidate: '請輸入電子信箱',
        emailValidate2: '請輸入正確格式的電子信箱',
        confirmEmail: '請再次輸入電子信箱',
        confirmEmailValidate: '兩次電子信箱不相符',
        passwordValidate: '請輸入密碼',
        confirmPasswordValidate: '請再次輸入密碼',
        confirmPasswordValidate2: '兩次密碼不相符',
        affiliationValidate: '請輸入所屬機構',
        jobTitleValidate: '請輸入職稱',
        idCardValidate: '請輸入身分證字號',
        idCardValidate2: '請輸入正確格式的身分證字號',
        countryValidate: '請選擇國家',
        countryCodeValidate: '請輸入國碼',
        phoneNumValidate: '請輸入手機號碼',
        categoryValidate: '請選擇類別',
        category1: '會員(台灣乳房腫瘤手術暨重建醫學會)',
        category2: '其他(包含護理人員、住院醫師、研究人員、學生... 等)',
        category3: '非會員',
        captcha: '驗證碼',
        remitAccountLast5Validate: '請輸入匯款帳號末五碼',
        remitAccountLast5Validate2: '匯款帳號末五碼必須為數字且為五碼',
    },
    en: {
        title: "Title",
        firstName: "First Name",
        lastName: "Last Name",
        chineseName: 'Chinese Name',
        email: 'Email',
        email2: 'Confirm Email',
        password: 'Password',
        confirmPassword: 'Confirm Password',
        affiliation: 'Affiliation',
        jobTitle: 'Job Title',
        idCard: 'ID Card Number',
        country: 'Country',
        remitAccountLast5: 'Last 5 Digits of Remittance Account',
        countryCode: 'Country Code',
        phoneNum: 'Phone Number',
        receipt: 'Receipt Title',
        category: 'Category',
        food: 'Dietary Preference',
        foodTaboo: 'Dietary Restrictions',
        foodRadio1: 'Non-Vegetarian',
        foodRadio2: 'Vegetarian',
        titleValidate: 'Please select a title',
        firstNameValidate: 'Please enter your first name',
        lastNameValidate: 'Please enter your last name',
        chineseNameValidate: '',
        emailValidate: 'Please enter your email',
        emailValidate2: 'Please enter a valid email address',
        confirmEmail: 'Please confirm your email',
        confirmEmailValidate: 'The email addresses do not match',
        passwordValidate: 'Please enter your password',
        confirmPasswordValidate: 'Please confirm your password',
        confirmPasswordValidate2: 'The passwords do not match',
        affiliationValidate: 'Please enter your affiliation',
        jobTitleValidate: 'Please enter your job title',
        idCardValidate: 'Please enter your ID card number',
        idCardValidate2: 'Please enter a valid ID card number',
        countryValidate: 'Please select your country',
        countryCodeValidate: 'Please enter your country code',
        phoneNumValidate: 'Please enter your phone number',
        categoryValidate: 'Please select a category',
        remitAccountLast5Validate: 'Please enter the last 5 digits of your remittance account',
        category1: 'Member (Taiwan Society of Breast Surgery and Reconstruction)',
        category2: 'Other (including nurses, resident doctors, researchers, students, etc.)',
        category3: 'Non-Member',
        captcha: 'Captcha',
        remitAccountLast5Validate2: 'The last 5 digits of the remittance account must be numeric and exactly 5 digits long',
    }
} as const

export type Locale = keyof typeof label