import { first } from "ckeditor5"

export const label = {
    zh: {
        title: "稱謂",
        firstName: "英文名",
        lastName: "英文姓氏",
        chineseName: '中文姓名',
        email: '電子信箱',
        email2: '電子信箱確認',
        password: '密碼(本次會議網站登入使用)',
        confirmPassword: '確認密碼',
        affiliation: '所屬機構',
        jobTitle: '職稱',
        idCard: '身分證字號(登入帳號)',
        country: '國家',
        remitAccountLast5: '匯款帳號末五碼',
        countryCode: '聯絡電話',
        phoneNum: '手機號碼',
        receipt: '發票抬頭',
        category: '類別',
        food: '餐食偏好',
        foodTaboo: '餐食禁忌',
        foodRadio1: '葷食',
        foodRadio2: '素食',
        titleValidate: '請選擇稱謂',
        firstNameValidate: '請輸入英文名',
        lastNameValidate: '請輸入英文姓氏',
        chineseNameValidate: '請輸入中文姓名',
        emailValidate: '請輸入電子信箱',
        emailValidate2: '請輸入正確格式的電子信箱',
        confirmEmail: '請再次輸入電子信箱',
        confirmEmailValidate: '兩次電子信箱不相符',
        passwordValidate: '請輸入密碼',
        confirmPasswordValidate: '請再次輸入密碼',
        confirmPasswordValidate2: '兩次密碼不相符',
        affiliationValidate: '請輸入所屬機構',
        jobTitleValidate: '請輸入職稱',
        idCardValidate: '請輸入身分證字號',
        idCardValidate2: '請輸入正確格式的身分證字號',
        countryValidate: '請選擇國家',
        countryCodeValidate: '請輸入國碼',
        phoneNumValidate: '請輸入手機號碼',
        categoryValidate: '請選擇類別',
        category1: '會員(台灣乳房腫瘤手術暨重建醫學會)',
        category2: '其他(包含護理人員、住院醫師、研究人員、學生... 等)',
        category3: '非會員',
        categoryExtra: '會員類別',
        captcha: '驗證碼',
        remitAccountLast5Validate: '請輸入匯款帳號末五碼',
        remitAccountLast5Validate2: '匯款帳號末五碼必須為數字且為五碼',
        abstractType: '摘要類別',
        abstractTitle: '摘要標題',
        firstAuthor: '第一作者',
        firstAuthorBirthday: '第一作者生日',
        speaker: '發表人',
        speakerAffiliation: '發表人所屬機構',
        correspondingAuthor: '通訊作者',
        correspondingAuthorMail: '通訊作者電子信箱',
        correspondingAuthorPhone: '通訊作者聯絡電話',
        allAuthors: '所有作者(請以分號分隔)',
        allAuthorsAffiliation: '所有作者所屬機構(請以分號分隔)',
        youngInvestigator: '年輕研究者',
        posterPresentation: '海報發表',
        videoPresentation: '影片發表',
        upload: '上傳',
        uploadLimit: '請上傳PDF檔，且檔案大小不可超過20MB',
        alreadyLogin: '您已經登入了',
        registrationSuccess: '註冊成功',
        pleaseEnterChineseName: '請輸入中文姓名',
        registrationReminder: '提醒：本次註冊後，網站會留存您的註冊資訊，供後續其他年度會議使用。',
        notPaid: '未付款',
        isQualified: '已具備與會資格。',
        profileIncomplete: '尚未具備與會資格',
        memberInfo: '已具備與會資格',
        editProfile: '編輯資料',
        profileReminder: '以下事項尚未完成，請儘速完成相關資料更新，以免影響後續稿件發表及與會權益。',
        resetForm: '還原資料'

    },
    en: {
        title: "Title",
        firstName: "First Name",
        lastName: "Last Name",
        chineseName: 'Chinese Name',
        email: 'Email',
        email2: 'Confirm Email',
        password: 'Password (For this conference website login)',
        confirmPassword: 'Confirm Password',
        affiliation: 'Affiliation',
        jobTitle: 'Job Title',
        idCard: 'Passport Number',
        country: 'Country',
        remitAccountLast5: 'Last 5 Digits of Remittance Account',
        countryCode: 'Country Code',
        phoneNum: 'Phone Number',
        receipt: 'Receipt',
        category: 'Category',
        food: 'Dietary Preference',
        foodTaboo: 'Dietary Restrictions',
        foodRadio1: 'Non-Vegetarian',
        foodRadio2: 'Vegetarian',
        titleValidate: 'Please select a title',
        firstNameValidate: 'Please enter your first name',
        lastNameValidate: 'Please enter your last name',
        chineseNameValidate: '',
        emailValidate: 'Please enter your email',
        emailValidate2: 'Please enter a valid email address',
        confirmEmail: 'Please confirm your email',
        confirmEmailValidate: 'The email addresses do not match',
        passwordValidate: 'Please enter your password',
        confirmPasswordValidate: 'Please confirm your password',
        confirmPasswordValidate2: 'The passwords do not match',
        affiliationValidate: 'Please enter your affiliation',
        jobTitleValidate: 'Please enter your job title',
        idCardValidate: 'Please enter your passport number',
        idCardValidate2: 'Please enter a valid passport number',
        countryValidate: 'Please select your country',
        countryCodeValidate: 'Please enter your country code',
        phoneNumValidate: 'Please enter your phone number',
        categoryValidate: 'Please select a category',
        remitAccountLast5Validate: 'Please enter the last 5 digits of your remittance account',
        category1: 'Member',
        category2: 'Other (including nurses, resident doctors, researchers, students, etc.)',
        category3: 'Non-Member',
        categoryExtra: 'Type of membership',
        captcha: 'Captcha',
        remitAccountLast5Validate2: 'The last 5 digits of the remittance account must be numeric and exactly 5 digits long',
        abstractType: 'Abstract Type',
        abstractTitle: 'Abstract Title',
        firstAuthor: 'First Author',
        firstAuthorBirthday: 'First Author Birthday',
        speaker: 'Speaker',
        speakerAffiliation: 'Speaker Affiliation',
        correspondingAuthor: 'Corresponding Author',
        correspondingAuthorMail: 'Corresponding Author Email',
        correspondingAuthorPhone: 'Corresponding Author Phone',
        allAuthors: 'All Authors (Use semicolon to separate authors)',
        allAuthorsAffiliation: 'All Authors Affiliation (Use semicolon to separate affiliations)',
        youngInvestigator: 'Young Investigator',
        posterPresentation: 'Poster Presentation',
        videoPresentation: 'Video Presentation',
        upload: 'Upload',
        uploadLimit: 'only upload pdf file with size less than 20mb',
        alreadyLogin: 'You are already logged in',
        registrationSuccess: 'Registration successful',
        pleaseEnterChineseName: 'Please enter your Chinese name',
        registrationReminder: 'Reminder: Your registration information will be retained for use in future annual meetings.',
        notPaid: 'Not Paid',
        isQualified: 'Qualified to attend the conference.',
        profileIncomplete: 'Not yet qualified to attend the conference',
        memberInfo: 'Qualified',
        editProfile: 'Edit Profile',
        profileReminder: 'The following items are incomplete. Please update your profile information as soon as possible to avoid affecting your manuscript submission and conference participation rights.',
        resetForm: 'Reset'
    }
} as const

export type Locale = keyof typeof label